/control/alias fiberEfficiency 1.0
/control/alias fiberResolution 50

/RES/Det/SetWorldX 50 cm
/RES/Det/SetWorldY 50 cm
/RES/Det/SetWorldZ 65 cm 

/RES/Gun/StartZ 30.0 cm

/RES/Det/AddLayer 3 22.7
/RES/Det/AddLayer 2 6.0
/RES/Det/AddLayer 2 -6.0
/RES/Det/AddLayer 3 -22.7

/RES/Det/SetLayerSubtractHoles 0 true
/RES/Det/SetLayerSubtractHoles 1 true
/RES/Det/SetLayerSubtractHoles 2 true
/RES/Det/SetLayerSubtractHoles 3 true
